X-Zalando-Team: "ncng"
X-Zalando-Type: code

commit:
  message:
    patterns:
      - "^(feat|fix|docs|style|refactor|perf|test|chore)\\(.*\\):"
approvals:
  minimum: 2
  ignore: none
  pattern: "^(:\\+1:|👍)$"
  veto:
    # veto/blocking a PR = comment that matches this regex
    pattern: "^(:\\-1:|👎)$"
